# Generated by Django 4.0.7 on 2023-04-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_song_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
    ]
